version: "3.7"

services:
  drupal:
    image: drupal
    ports:
      - "8080:80"
    networks:
      - drupal_network
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: "drupal"
      POSTGRES_USER: "drupal"
      POSTGRES_PASSWORD: "drupal"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - drupal_network

networks:
  drupal_network:
